### ISSUE TITLE
Set Cookie

### ISSUE THREAD

**Issue by qamukova** [IliaIdakiev/softuni-js-backend#1]
Здравейте! Може ли малко помощ относно това защо в конзолата на браузъра в Application/Storage/Cookies не се показва кукито, което генерирам? А в Response Headers от заявката, която е успешна имам Set-Cookie. Очевидно се генерира такова и кода работи, но въпреки това има проблем, за да не го виждам в Cookies?

 router.post('/login', (req, res, next) => {
    const { username, password } = req.body;
    models.User.findOne({ username })
        .then(user => Promise.all([user, user ? user.comparePasswords(password) : false]))
        .then(([user, match]) => {
            if(!match) { res.send('Wrong password or username!'); return; }
            return Promise.all([user, modules.jwt.createToken({ id: user._id })]);
        }).then(([user, token]) => {
            res.cookie('auth_cookie', token, { httpOnly: true });
            res.send(user);
        }).catch(next);
});

**Comment by IliaIdakiev** [comment]
@qamukova Виж дали като пращаш заявкава от браузъра си сложила credentials: true (това е ако ползваш fetch), ако не ползваш fetch, може би просто трябва да натиснеш refresh бутона, който се намира до filter полето
![image](https://user-images.githubusercontent.com/1511551/97861870-22c44300-1d0d-11eb-9fb5-38cc9cd24ded.png)

**Comment by qamukova** [comment]
Благодаря, но пропуснах да спомена, че използвам Angular с NgRX за frontend частта. Може би там пропускам нещо?

**Comment by IliaIdakiev** [comment]
В такъв случай, като правиш http заявката трябва да имаш withCredentials: true в options. Това се отнася за всички заявки, които ще ползват cookie-то.

**Comment by qamukova** [comment]
Да, това беше точно проблема, нямах withCredentials. Благодаря, много!
